### ISSUE TITLE
Faltando CSS no botão do quiz

### ISSUE THREAD

**Issue by moniquedsilva** [RodCerB/singlepagesite#1]
Ficou faltando aplicar o CSS no botão do quiz.
Inclua o id dele dentro do arquivo CSS, onde tem o id do botão do form.

Antes:
```css
#plugHunter_btn {
  width: 80px;
  height: 30px;
  font-family: "Roboto", sans-serif;
}
```

Depois:
```css
#plugHunter_btn, #button_quiz {
  width: 80px;
  height: 30px;
  font-family: "Roboto", sans-serif;
}
```
